version: '3'

services:
    klaus:
        container_name: klaus
        build:
            context: .
            dockerfile: Dockerfile
        image: jwansek/klaus
        user: "1002:1000"
        environment:
            - APP_THREADS=4
        volumes:
            - '/media/git:/srv/git:ro'
            - '/media/gitwww/repositories:/srv/repos:ro'
        ports:
            - '81:80'
        restart: always
